--// Generated by roblox-c v1.0.0 \\--
--Note: This code will not be very clean.

local C = require(game.ReplicatedStorage:WaitForChild("Packages").cruntime)


local RED = 0 -- enum: Color
local GREEN = 1 -- enum: Color
local BLUE = 2 -- enum: Color

function print_color(color)
	if color==RED  then
		print("hi")
	else
		if color==GREEN  then
			print("hi")
		else
			print("hi")
		end
	end
end
function add(a, b)
	return a+b 
end
function greet(name)
	print("hi")
end
function call_functions()
	greet("Alice")
	local sum = add(2, 3)print("hi")
end