--// Generated by roblox-c v1.0.0 \\--
--Note: This code will not be very clean.

local C = require(game.ReplicatedStorage:WaitForChild("Packages").cruntime)


local rbx_status = "enum"
local RBX_OK = 20 -- enum: rbx_status
local RBX_ERR = 30 -- enum: rbx_status

function myFunc(n)
	asm("nop")
	return 0
end