--// Generated by roblox-c v1.0.0 \\--
--Note: This code will not be very clean.

local C = require(game.ReplicatedStorage:WaitForChild("Packages").cruntime)

printf = C.printf

local function namespace_myNamespace()
	local my_variable = 42
	function my_function()
	end
	local MyClass = {
	}
	return {
		[my_variable] = my_variable,
		[my_function] = my_function,
		[MyClass] = MyClass,
	}
end
local myNamespace = namespace_myNamespace()
local my_variable = myNamespace["my_variable"]
local my_function = myNamespace["my_function"]
local MyClass = myNamespace["MyClass"]
do
	printf("%d\n", my_variable)
end