import sys, os, json
import crun
#### LOG #####
def error(msg):
    sys.stderr.write("\033[91;1merror\033[0m \033[90mC roblox-c:\033[0m " + msg + "\n")
    sys.exit(1)
def warn(msg):
    sys.stderr.write("\033[1;33m" + "warning: " + "\033[0m" + "\033[90mC roblox-c:\033[0m " + msg + "\n")
def info(msg):
    sys.stderr.write("\033[1;32m" + "info: " + "\033[0m" + "\033[90mC roblox-c:\033[0m " + msg  + "\n")
    
    
#### CONSTANTS ####
CONFIG_FILE = os.path.expanduser('~/.config/rbxc/config.json')
VERSION = "1.1.0"
TAB = "\t\b\b\b\b"

#### DEPENDENCIES ####
try:
    import clang.cindex as clang
    from clang.cindex import Config
except ImportError:
    error("libclang could not be resolved")

try:
    import luaparser
    from luaparser.ast import *
    from luaparser.astnodes import *
except ImportError:
    error("luaparser could not be resolved")
    
#### COMPILER PARSER ####
bins = {
    "!": "not ",
    "||": " or ",
    "&&": " and ",
    "==": "==",
    "!=": "~=",
    "<": "<",
    ">": ">",
    "<=": "<=",
    ">=": ">=",
    "**":"^",
    "]": " + 1] ",
    "<<": "/C.bitlshift()*",
    ">>": "/C.bitrshift()*",
    "|": "/C.bor()*",
    "&": "/C.band()*",
    "^": "/C.bxor()*",
}
uns = {
    "++": {
        "v":" += 1",
        "wrap": False,
    },
    "**": {
        "v":"^",
        "wrap": False,
    },
    "--": {
        "v":" -= 1",
        "wrap": False,
    },
    "&": {
        "v":"C.ptr(",
        "wrap": True,
    },
    "*": {
        "v":"C.deref(",
        "wrap": True,
    },
    "!": {
        "v":"not ",
        "wrap": False,
    },
    "sizeof": {
        "v":"C.sizeof(",
        "wrap": True,
    },
    "sizeof...": {
        "v":"C.sizeof(",
        "wrap": True,
    },
    "alignof": {
        "v":"C.alignof(",
        "wrap": True,
    },
    "__real": {
        "v":"C.__real(",
        "wrap": True,
    },
    "__imag": {
        "v":"C.__imag(",
        "wrap": True,
    }
}
def get_ast(file_path, c, check=True, flags=[]):
    if check:
        test(file_path, c, flags)
    try:
        index = clang.Index.create()
        if c:
            std = "c99"
        else:
            std = "c++11"
        translation_unit = index.parse(file_path, args=['-std='+std])
        return translation_unit.cursor
    except clang.LibclangError as e:
        error("libclang error: " + str(e))
        sys.exit(1)
    except Exception as e:
        error(str(e))
        sys.exit(1)
def print_ast(node, depth=0):
    print('  ' * depth + str(node.kind) + ' : ' + node.spelling)
    for child in node.get_children():
        print_ast(child, depth + 1)
def test(file_path, c, flags):
    # Runs gcc on the file to check for errors, if there is an error sys.exit(1)
    if c:
        iserrors = os.system("gcc -fsyntax-only -D__RCC__=1 " + " ".join(flags) + " " + file_path)
    else:
        iserrors = os.system("g++ -fsyntax-only -D__RCC__=1 " + " ".join(flags) + " " + file_path)
    if iserrors != 0:
        sys.exit(1)

#### GENERATOR ####
class NodeVisitor(object):
    def __init__(self, isC):
        self.indent = 0
        self.ast = None
        if isC:
            self.lang = "C"
        else:
            self.lang = "C++"
            self.namespaces = {}

    ### VISITORS ###
    def visit_translation_unit(self, node):
        self.ast = Chunk(Block([self.visit(child) for child in node.get_children()]))
    
    
    ### NODESYSTEM ###
    def visit(self, node):
        method = 'visit_' + node.kind.name.lower()
        visitor = getattr(self, method, self.generic_visit)
        return visitor(node)
    def generic_visit(self, node):
        pass
        #error(f"{node.kind.name.lower()} not implemented")
    def gen(self):
        return to_lua_source(self.ast)

#### HEADER ####
REQUIRE = "local C = require(game.ReplicatedStorage:WaitForChild(\"Packages\").cruntime)\n\n"
HEADER = "--// Generated by roblox-c v" + VERSION + " \\\\--\n"+REQUIRE
LIBS = ["malloc", "free", "realloc", "calloc", "memset", "memcpy", "memmove", "memcmp", "memchr", "printf"]

def gen(code):
    header = ""
    for lib in LIBS:
        if lib in code:
            header += lib+" = C."+lib+"\n"
    return header
#### INTERFACE #### 
def check():
    if not os.path.exists(os.path.expanduser('~/.config/rbxc')):
        os.makedirs(os.path.expanduser('~/.config/rbxc'))
    if not os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, 'w') as f:
            json.dump({}, f)
def config(key, value):
    check()
    # Load existing config file or create a new one if it doesn't exist
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, 'r') as f:
            config_data = json.load(f)
    else:
        config_data = {}

    # Update the config with the new key-value pair
    config_data[key] = value

    # Save the updated config to disk
    with open(CONFIG_FILE, 'w') as f:
        json.dump(config_data, f)
def isconfig(key):
    check()
    # Load the config file
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, 'r') as f:
            config_data = json.load(f)
    else:
        config_data = {}

    # Return the value of the specified key, or None if it doesn't exist
    return config_data.get(key)  

def usage():
    print("\n"+f"""usage: \033[1;94mrbxc\033[0m [file] [options] -o [gen]
\033[1mOptions:\033[0m
{TAB}\033[1m-v\033[0m        show version information
{TAB}\033[1m-c\033[0m        debug mode
{TAB}\033[1m-s\033[0m        generate cruntime
{TAB}\033[1m-o\033[0m        output file
{TAB}\033[1m-vd\033[0m       show version number only
{TAB}\033[1m-p\033[0m        set libclang path
{TAB}\033[1m-u\033[0m        open this
{TAB}\033[1;31m-h\033[0m\033[31m        hardcore mode\033[0m""")
    sys.exit()
def version():
    print("\033[1;34m" + "copyright:" + "\033[0m" + " roblox-py " + "\033[1m" + VERSION + "\033[0m" + " licensed under the MIT License by " + "\033[1m" + "@AsynchronousAI" + "\033[0m")
    sys.exit(0)
def main():
    # read args
    args = sys.argv[1:]
    flags = []
    inputf = None
    outputf = None
    check = True

    lookForOutput = False
    skip = False
    hardcore = False
    
    if isconfig("lclang"):
        Config.set_library_file(isconfig("lclang"))
        
    flags = []
    
    for i, arg in enumerate(args):
        if arg.startswith("-W"):
            flags.append(arg)
        elif arg == "-o":
            lookForOutput = True
        elif arg == "-c":
            check = False
        elif arg == "-h":
            hardcore = True
        elif arg == "-p":
            try:
                Config.set_library_file(args[i+1])
                config("lclang", args[i+1])
                skip = True
            except:
                config("lclang", None)
                error("no path specified")
                sys.exit(1)
        elif arg == "-v":
            version()
        elif arg == "-vd":
            print(VERSION)
            sys.exit(0)
        elif arg == "-u":
            usage()
        elif arg.startswith("-"):
            flags.append(arg)
        elif (inputf is None) and "-s" not in args:
            inputf = arg
        elif lookForOutput:
            outputf = arg
            lookForOutput = False
        elif skip:
            skip = False
        else:
            error("too many arguments")
            sys.exit(1)
    
    if (inputf is None) and "-s" not in args:
        usage()
        sys.exit(1)
    
    if outputf is None:
        error("no output file specified")
        sys.exit(1)
        
    if "-s" in args:
        print(crun.cruntime)
        sys.exit(0)
    
    isC = None
    if inputf.endswith(".c"):
        isC = True
    elif inputf.endswith(".cpp") or inputf.endswith(".cxx") or inputf.endswith(".cc") or inputf.endswith(".C"):
        isC = False
    else:
        error("file must end with '.c', '.cpp', '.cxx', '.cc', or '.C'")
        sys.exit(1)
        
    parsed = get_ast(inputf, isC, check, flags)
    if not check:
        print_ast(parsed)
    Engine = NodeVisitor(isC)
    Engine.visit(parsed)
    Enginecode = Engine.gen()
    with open(outputf, "w") as f:
        code = (HEADER + gen(Enginecode) + Enginecode)
        if hardcore:
            code = "xpcall(function() -- hardcore mode\n" + code + "\nend, function(err) -- hardcore mode\n\terror('Segmenation fault: 11') -- hardcore mode\nend) -- hardcore mode"
            
        f.write(code)
    
if __name__ == "__main__":
    main()